markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Some Might Say"

author: "hanlin"
atom-baseurl: "http://hanlin.ch"

navigations:
  - title: Archive
    class: fa fa-archive
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html 
  - title: Instagram
    class: fa fa-instagram
    href: http://instagram.com/onion7878/
  - title: VSCO Grid
    class: fa fa-th-large
    href: http://onion7878.vsco.co/
  - title: Twitter
    class: fa fa-twitter
    href: https://twitter.com/4fen   
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

