markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "Some Might Say"

author: "hanlin"
atom-baseurl: "http://hanlin.ch"

navigations:
  - title: Archive
    class: fa fa-archive
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Again
    class: fa fa-bookmark
    href: /again.html    
  - title: Instagram
    class: fa fa-instagram
    href: http://instagram.com/onion7878/
  - title: Twitter
    class: fa fa-twitter
    href: https://twitter.com/4fen   
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

